In [1]:
import pandas as pd
import json
import os

In [2]:
file = "data/artists_info/0A0FS04o6zMoto8OKPsDwY.json"
with open(file) as f:
    data = json.load(f)

artist = data['name']
followers = data['followers']['total']
artist_id = data['id']
popularity = data['popularity']

data = pd.DataFrame({"artist_id": artist_id, "artist": artist, "followers": followers, "popularity": popularity}, index=[0])
data

                artist_id artist  followers  popularity
0  0A0FS04o6zMoto8OKPsDwY     YG    3197882          72

In [3]:
file2 = "data/artists_discography/0AlNB0yIoyxdKloLmK9AOR/1NPsRg5FZo8FtoSl2p4LWz.json"
with open(file2) as f:
    data2 = json.load(f)

track_name = data2['name']
track_id = data2['id']
popularity = data2['popularity']
duration = data2['duration_ms']
explicit = data2['explicit']

# create a row
data2 = pd.DataFrame({'track_id': [track_id], 'track_name': [track_name], 'popularity': [popularity], 'duration': [duration], 'explicit': [explicit]})
data2

                 track_id track_name  popularity  duration  explicit
0  1NPsRg5FZo8FtoSl2p4LWz       Burn          34    244400     False

In [4]:
with open(file2) as f:
    data3 = json.load(f)

#display(data3)
track_id = data3['id']
artists = [artist['id'] for artist in data3['artists']]

data3 = pd.DataFrame({'track_id': track_id, 'artist_id': artists})
data3

                 track_id               artist_id
0  1NPsRg5FZo8FtoSl2p4LWz  0AlNB0yIoyxdKloLmK9AOR
1  1NPsRg5FZo8FtoSl2p4LWz  66VgJGpaRMwrNaS2MPqIDf

In [5]:
file4 = "data/tracks_audio_features/0A0oeqd0qXsmsmy8PeCDEt.json"
with open(file4) as f:
    data4 = json.load(f)

data4 = pd.DataFrame(data4, index=[0])
data4 = data4.drop(columns=['type', 'uri', 'track_href', 'analysis_url'])
data4 = data4.rename(columns={"id": "track_id"})
data4

,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,track_id,duration_ms,time_signature
0,0.659,0.919,9,-2.707,1,0.0809,0.00759,0.00233,0.125,0.148,114.985,0A0oeqd0qXsmsmy8PeCDEt,358983,4

----

In [6]:
# GET ALL THE ARTISTS FROM data/artists_info/X.json
artists_info_path = "data/artists_info"
files = os.listdir(artists_info_path)
files = [artists_info_path + "/" + file for file in files if file.endswith(".json")]
files

artists = pd.DataFrame()
for file in files:
    with open(file) as f:
        data = json.load(f)

    temp = pd.DataFrame({"artist_id": data['id'], "artist": data['name'], "followers": data['followers']['total'], "popularity": data['popularity']}, index=[0])
    artists = pd.concat([artists, temp])

artists = artists.reset_index(drop=True)
artists = artists.drop_duplicates()
artists

os.makedirs("export", exist_ok=True)
artists.to_csv("export/artists.csv", index=False)

In [7]:
tracks_path = "data/artists_discography"
artists = os.listdir(tracks_path)
artists

tracks = pd.DataFrame()
for artist in artists:
    for track in os.listdir(tracks_path + "/" + artist):
        with open(tracks_path + "/" + artist + "/" + track) as f:
            data = json.load(f)

        temp = pd.DataFrame({"track_id": data['id'], "track_name": data['name'], "popularity": data['popularity'], "explicit": data['explicit']}, index=[0])
        temp = temp.rename(columns={"id": "track_id"})
        tracks = pd.concat([tracks, temp])

tracks = tracks.reset_index(drop=True)
tracks = tracks.drop_duplicates()
tracks

,track_id,track_name,popularity,explicit
0,5nlPMUOXOIxsFlaVuTx8YR,Future - Bit Funk Remix,0,False
1,57Bxw40gSyf5QlF9VQEM9Z,Blow Ya House,1,False
2,7d5OwE3UyHYGlsCSSw0GAB,Double Down,9,False
3,1A4SsoEro9KzvIl3UmT03F,Lil Mama - Golf Clap Remix,7,False
4,0bRFqihE0KyqCqfbx5ASqB,Freak,0,False
...,...,...,...,...
31996,5osW3HfNbbsA9Iy2Wxn1YB,Fortune Days - Ambient Version,22,False
31997,2Ej1MefL97ClVIn1UHtOVC,Bad Wings - Kastle Remix,16,False
31998,0i6xXrlhCdKh7N8GllP6L9,Take Me with You (Remix) X We Can Make the Wor...,28,False
31999,4q1q6kCMwDf5YUsOkTPBLE,"Starve The Ego, Feed The Soul",41,False
32000,5zyEVonJpHJTBm4GcwM93C,How To Be Eaten By A Woman - Ambient Version,23,False

In [8]:
tracks_audio_features_path = "data/tracks_audio_features"
tracks_ = os.listdir(tracks_audio_features_path)
tracks_

audio_features = pd.DataFrame()
for track in tracks_:
    with open(tracks_audio_features_path + "/" + track) as f:
        data = json.load(f)

    temp = pd.DataFrame(data, index=[0])
    temp = temp.drop(columns=['type', 'uri', 'track_href', 'analysis_url'])
    temp = temp.rename(columns={"id": "track_id"})
    audio_features = pd.concat([audio_features, temp])

audio_features = audio_features.reset_index(drop=True)
audio_features = audio_features.drop_duplicates()
audio_features

,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,track_id,duration_ms,time_signature
0,0.797,0.656,5,-5.740,1,0.0948,0.096100,0.490000,0.0461,0.344,149.998,19wgIwKRVTuKbKJB0lnCG5,153200,4
1,0.560,0.487,3,-5.640,1,0.0303,0.429000,0.000000,0.1070,0.469,74.020,0tooLMhjLCJ4Cmb8cDdraJ,189004,4
2,0.792,0.969,1,-4.676,1,0.0834,0.007640,0.079500,0.3800,0.425,129.961,5ZL2nl1Omw8YB3YLbniOZ3,169846,4
3,0.726,0.827,0,-8.105,1,0.0434,0.013500,0.000264,0.2090,0.778,135.008,3ClKsM5f06HfEpzNhmQeY0,173333,4
4,0.622,0.903,2,-6.505,1,0.0489,0.000643,0.087600,0.3720,0.237,129.958,1fihIezoIphfPl2TK2A7RJ,240000,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31138,0.618,0.400,1,-9.776,1,0.0734,0.000235,0.000000,0.7380,0.133,75.047,4zwSuVPORpri4LYy50J3J7,217587,4
31139,0.652,0.807,4,-5.757,0,0.0304,0.002240,0.000000,0.1770,0.564,105.023,6Oa9kwZJ1TJDXpyChQTWiG,193427,4
31140,0.529,0.527,3,-7.536,1,0.0343,0.414000,0.000577,0.3140,0.131,125.969,3mLbG16WHshM17CFxvXhCG,236533,4
31141,0.632,0.609,7,-6.782,1,0.1410,0.047400,0.000514,0.1930,0.383,157.984,1RNIK8ZZVFK9oT4YCD9Kkm,173165,4
31142,0.401,0.945,4,-5.984,1,0.2160,0.001880,0.000000,0.3250,0.408,174.953,2q1xAFwYcZ5biNMqweMCYG,177840,4

In [9]:
tracks = pd.merge(tracks, audio_features, on="track_id", how="outer")
tracks = tracks.drop_duplicates()
tracks.to_csv("export/tracks.csv", index=False)

In [10]:
artist_tracks = pd.DataFrame()
for artist in artists:
    for track in os.listdir(tracks_path + "/" + artist):
        with open(tracks_path + "/" + artist + "/" + track) as f:
            data = json.load(f)

        temp = pd.DataFrame({"track_id": data['id'], "artist_id": [artist['id'] for artist in data['artists']]})
        artist_tracks = pd.concat([artist_tracks, temp])

artist_tracks = artist_tracks.reset_index(drop=True)
artist_tracks = artist_tracks.drop_duplicates()
artist_tracks.to_csv("export/artists_tracks.csv", index=False)